name: Build and Run

on: [push, pull_request]

jobs:
  build:

strategy:
      matrix:
        configuration: [Debug]
        
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Normal Run
      run: javac SenderPart/Sender.java
      
    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101

    - name: Run tests and collect coverage
      run: dotnet test --collect:"XPlat Code Coverage"
      
    - run: |
          #bash echo "$PWD"
